description: wmt25-compression-task

target:
    service: sing
    name: ast-sing-prod02-eus  # A100 cluster

environment:
    registry: thammegowda.azurecr.io
    #image: wmt25-model-compression:v1


    ## NOTE: set SUB_ID variable before calling amlt run
    # for s in mcptqsr tcd-kreasof mcsr-wmt25 vicomtech; do echo SUB_ID=$s amlt run amlt/a100.yml :job=$s; done
    image: wmt25-modelzip-submission:$SUB_ID

    setup:
      - echo "==== MY SETUP BEGIN ===="
      - git config --global credential.helper store
      - echo "==== MY SETUP END ===="
code:
    local_dir: $CONFIG_DIR/..

storage:
    drive1:
      storage_account_name: tgwus2
      container_name: data
      mount_dir: /mnt/tg/data
      is_output: True

jobs:
    - name: job
      sku: 80G1
      #identity: managed
      #process_count_per_node: 1
      submit_args: &sargs
        env:
          AMLT_DOCKERFILE_TEMPLATE: none
      command:
        - sleep 3d
    - name: sanity
      sku: 80G1
      submit_args: *sargs
      command:
        - bash evals/sanitycheck.sh


